#!/bin/bash
# checks if $LD_LIBRARY_PATH is set after setup_platform
cvm_test_name="check_LD_LIBRARY_PATH_after_setup_systemapps"
tags=("-i" "-h")
cvm_run_test() {
  if ! run_docker_inside $t/script.sh || ! run_podman_inside $t/script.sh; then
    return 1
  fi

  return 0
}

