#!/bin/bash
# runs cernvm_config setup_platform 
cvm_test_name="run_setup_platform_without_cvmfs"
tags=("-i")
cvm_run_test() {
  run_docker_inside $t/script.sh
  res=$?
  log "Test $cvm_test_name returned $res (must fail)"
  if [ $res -eq 0 ]; then
    return 1
  fi
  return 0
}

