#!/bin/bash
# runs cernvm_config setup_userapps with CernVM FS mounted from host
cvm_test_name="run_setup_userapps_with_host"
tags=("-h")
cvm_run_test() {
  run_docker_host $t/script.sh
  res=$?
  log "Test $cvm_test_name returned $res"
  return $res
}

