#!/bin/bash
cvm_test_name="LD_LIBRARY_PATH"

# checks if $LD_LIBRARY_PATH is set
cvm_run_test() {
  if [[  "$LD_LIBRARY_PATH" != "" ]]; then
        log "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
        return 1
  fi
log "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"
  return 0
}

