#!/bin/bash
# runs /mount.sh with host CernVM FS
cvm_test_name="run_mount_script_with_host"
tags=("-h")
cvm_run_test() {
  run_docker_host $t/script.sh
  res=$?
  log "Test $cvm_test_name returned $res"
  return $res
}

