#!/bin/bash
# checks for unintentionally locally installed applications
cvm_test_name="check_local_userapps"
tags=("-i" "-h")
cvm_run_test() {
  if ! run_docker_inside $t/script.sh || ! run_podman_inside $t/script.sh; then
    return 1
  fi

  return 0
}s


