#!/bin/bash
# Sets up fcc stack and checks dnf wrapper function
cvm_test_name="fcc-setup_fcc_check_dnf_wrapper"
tags=("-h","-i")
cvm_run_test() {
  if ! run_docker_inside $t/script.sh || ! run_podman_inside $t/script.sh; then
    return 1
  fi

  return 0
}