#!/bin/bash
# Sets up fcc stack and checks dnf wrapper function
cvm_test_name="fcc-setup_fcc_check_dnf_wrapper"
tags=("-h","-i")
cvm_run_test() {
  run_docker_host $t/script.sh
  res=$?
  log "Test $cvm_test_name returned $res"
  return $res
}


