#!/bin/bash
# checks if $LD_LIBRARY_PATH is set
cvm_test_name="check_LD_LIBRARY_PATH"
tags=("-i" "-h")
cvm_run_test() {
  run_docker_inside $t/script.sh
  res=$?
  log "Test $cvm_test_name returned $res"
  return $res
}

