#!/bin/bash
# checks applications on CernVM FS
cvm_test_name="check_cvmfs_userapps_inside"
tags=("-i")
cvm_run_test() {
  run_docker_inside $t/script.sh
  res=$?
  log "Test $cvm_test_name returned $res"
  return $res
}


