#!/bin/bash
# runs cernvm_config setup_systemapps with CernVM FS mounted from host
cvm_test_name="run_setup_systemapps_with_host"
tags=("-h")
cvm_run_test() {
  if ! run_docker_host $t/script.sh || ! run_podman_host $t/script.sh; then
    return 1
  fi

  return 0
}