#!/bin/bash
# checks applications on CernVM FS with CernVM FS form host
cvm_test_name="check_cvmfs_userapps_with_host"
tags=("-h")
cvm_run_test() {
  run_docker_host $t/script.sh
  res=$?
  log "Test $cvm_test_name returned $res"
  return $res
}


