#!/bin/bash
# checks applications on CernVM FS
cvm_test_name="check_cvmfs_systemapps_inside"
tags=("-i")
cvm_run_test() {
  if ! run_docker_inside $t/script.sh || ! run_podman_inside $t/script.sh; then
    return 1
  fi

  return 0
}