#!/bin/bash
# checks for unintentionally locally installed applications
cvm_test_name="check_local_userapps"
tags=("-i" "-h")
cvm_run_test() {
  run_docker_inside $t/script.sh
  res=$?
  log "Test $cvm_test_name returned $res"
  return $res
}


