#!/bin/bash
# Sets up fcc stack, then platform  and checks userapps
cvm_test_name="fcc-setup_fcc_setup_platform_check_userapps"
tags=("-h","-i")
cvm_run_test() {
  run_docker_host $t/script.sh
  res=$?
  log "Test $cvm_test_name returned $res"
  return $res
}


