#!/bin/bash
# Sets up systemapps, then fcc stack and checks systemapps with CVMFS mounted inside
cvm_test_name="fcc-setup_systemapps_setup_fcc_check_systemapps_inside"
tags=("-i")
cvm_run_test() {
  if ! run_docker_inside $t/script.sh || ! run_podman_inside $t/script.sh; then
    return 1
  fi

  return 0
}