#!/bin/bash
# checks config files for cernvm-five.cern.ch
cvm_test_name="check_cvmfs_config_files"
tags=("-i" "-h")
cvm_run_test() {
  if ! run_docker_inside $t/script.sh || ! run_podman_inside $t/script.sh; then
    return 1
  fi

  return 0
}