#!/bin/bash
# Sets up fcc stack, then systemapps  and checks systemapps
cvm_test_name="fcc-setup_fcc_setup_systemapps_check_systemapps_inside"
tags=("-i")
cvm_run_test() {
  if ! run_docker_inside $t/script.sh || ! run_podman_inside $t/script.sh; then
    return 1
  fi

  return 0
}


