#!/bin/bash
# Sets up fcc stack, then systemapps  and checks systemapps with CVMFS mounted from host
cvm_test_name="fcc-setup_fcc_setup_systemapps_check_systemapps_host"
tags=("-h")
cvm_run_test() {
  if ! run_docker_host $t/script.sh || ! run_podman_host $t/script.sh; then
    return 1
  fi

  return 0
}


