#!/bin/bash
# runs /mount.sh without CernVM FS mounted from host
cvm_test_name="run_mount_script_without_host"
tags=("-i")
cvm_run_test() {
  run_docker_inside $t/script.sh
  res=$?
  log "Test $cvm_test_name returned $res"
  return $res
}

