#!/bin/bash
# runs mount_cvmfs -u with host CernVM FS, must return !=0
cvm_test_name="run_mount_cvmfs-u_with_host"
tags=("-h")
cvm_run_test() {
  run_docker_host $t/script.sh
  res=$?
  log "Test $cvm_test_name returned $res (must fail)"
  if [ $res -eq 0 ]; then
    return 1
  fi
  return 0
}

