#!/bin/bash
# checks if /data readable and writeable for container
cvm_test_name="check_data "
tags=("-i" "-h")
cvm_run_test() {
  cp **/$t/pre/* $data_host
  if ! run_docker_inside $t/script.sh || ! run_podman_inside $t/script.sh; then
    return 1
  fi

  return 0
}