#!/bin/bash
# Performs a fcc integration test
# 
cvm_test_name="fcc-whizard_inside"
tags=("-i")
cvm_run_test() {
  if ! run_docker_inside $t/script.sh || ! run_podman_inside $t/script.sh; then
    return 1
  fi

  return 0
}