#!/bin/bash
# runs cernvm_config setup_userapps with CernVM FS from in Container
cvm_test_name="run_setup_userapps_inside"
tags=("-i")
cvm_run_test() {
  run_docker_inside $t/script.sh
  res=$?
  log "Test $cvm_test_name returned $res"
  return $res
}

