#!/bin/bash
# runs cernvm_config setup_userapps with CernVM FS from in Container
cvm_test_name="run_setup_userapps_inside"
tags=("-i")
cvm_run_test() {
  if ! run_docker_inside $t/script.sh || ! run_podman_inside $t/script.sh; then
    return 1
  fi

  return 0
}