#!/bin/bash
# Performs a fcc integration test
# 
cvm_test_name="fcc-whizard"
tags=("-h","-i")
cvm_run_test() {
  run_docker_host $t/script.sh
  res=$?
  log "Test $cvm_test_name returned $res"
  return $res
}