#!/bin/bash
# checks if /workspace readable and writeable for container
cvm_test_name="check_workspace "
tags=("-i" "-h")
cvm_run_test() {
  cp **/$t/pre/* $workspace_host
  run_docker_inside $t/script.sh
  res=$?
  rm -f $workspace_host/*
  log "Test $cvm_test_name returned $res"
  return $res
}

