### This file is part of CernVM 5. ### 
### Used to prepare FCC starterkit image ###
FROM registry.cern.ch/cernvm/five/cernvm-five:latest
WORKDIR /populate
COPY ./populate.sh /populate
CMD [ "bash", "populate.sh" ]