#!/bin/bash
# Sets up userapps, then fcc stack and checks userapps
cvm_test_name="fcc-setup_userapps_setup_fcc_check_userapps"
tags=("-h","-i")
cvm_run_test() {
  run_docker_host $t/script.sh
  res=$?
  log "Test $cvm_test_name returned $res"
  return $res
}


