#!/bin/bash
# Sets up userapps, then fcc stack and checks userapps
cvm_test_name="fcc-setup_userapps_setup_fcc_check_userapps"
tags=("-h","-i")
cvm_run_test() {
  if ! run_docker_inside $t/script.sh || ! run_podman_inside $t/script.sh; then
    return 1
  fi

  return 0
}